### ISSUE TITLE
Modify to use Ansible API V2

### ISSUE THREAD

**Issue by MrMMorris** [verygood-ops/citadel-ansible#7]
I have reached a point where I cannot put off moving to Ansible 2.0 any longer and this plugin is essentially the only thing preventing me from doing so. I am not well versed in Python or the Ansible API so I am creating this issue to use on Bountry Source.

https://www.bountysource.com/issues/30020306-modify-to-use-ansible-api-v2

**Comment by mahmoudimus** [comment]
@MrMMorris I had no idea that this was preventing movement to Ansible-v2. I'll take a look.
